# Generated by Django 3.2.8 on 2022-06-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vanne',
            name='onoff',
            field=models.BooleanField(default=False),
        ),
    ]
