# Generated by Django 3.2.8 on 2022-07-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_capsol'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapSol2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devId', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Ec', models.FloatField(null=True)),
                ('Sal', models.FloatField(null=True)),
                ('Bat', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
