# Generated by Django 3.2.8 on 2022-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_capsol2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(null=True)),
                ('Humidity', models.FloatField(null=True)),
                ('Vent', models.FloatField(null=True)),
                ('Rafale', models.FloatField(null=True)),
                ('Pluv', models.FloatField(null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
    ]
