# Generated by Django 3.2.8 on 2022-07-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_ws'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsol',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
