# Generated by Django 3.2.8 on 2022-07-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_capsol_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Device', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Ray', models.FloatField(null=True)),
                ('Wind_Speed', models.FloatField(null=True)),
                ('Rain', models.FloatField(null=True)),
                ('Wind_Dir', models.CharField(max_length=50, null=True)),
                ('Time_Stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
