# Generated by Django 3.2.8 on 2022-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_ws_ray'),
    ]

    operations = [
        migrations.AddField(
            model_name='ws',
            name='dateRay',
            field=models.DateTimeField(null=True),
        ),
    ]
