# Generated by Django 3.2.8 on 2022-07-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_ws_dateray'),
    ]

    operations = [
        migrations.RenameField(
            model_name='et0',
            old_name='e',
            new_name='Hmax',
        ),
        migrations.RenameField(
            model_name='et0',
            old_name='ew',
            new_name='Hmin',
        ),
        migrations.RenameField(
            model_name='et0',
            old_name='ewTmax',
            new_name='Raym',
        ),
        migrations.RenameField(
            model_name='et0',
            old_name='ewTmin',
            new_name='Tmax',
        ),
        migrations.RenameField(
            model_name='et0',
            old_name='ewTmoy',
            new_name='Tmin',
        ),
    ]
