# Generated by Django 3.2.8 on 2022-07-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20220723_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='et0',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='Delta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='Hmax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='Hmin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='Raym',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='Time_Stamp',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='Tmax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='Tmin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='U2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='WSavg',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
