# Generated by Django 3.2.8 on 2022-07-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20220724_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='et0',
            name='Time',
        ),
        migrations.AlterField(
            model_name='et0',
            name='Time_Stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
