# Generated by Django 3.2.8 on 2022-07-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20220724_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='et0',
            name='Time_Stamp',
            field=models.DateField(auto_now=True),
        ),
    ]
