# Generated by Django 3.2.8 on 2022-07-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_et0_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='et0',
            name='Time_Stamp',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='et0',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
