# Generated by Django 3.2.8 on 2022-07-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_auto_20220724_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='et0',
            name='dt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
