# Generated by Django 3.2.8 on 2022-07-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_et0_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFwi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ffmc', models.FloatField()),
                ('dmc', models.FloatField()),
                ('dc', models.FloatField()),
                ('isi', models.FloatField()),
                ('bui', models.FloatField()),
                ('fwi', models.FloatField()),
            ],
        ),
    ]
