# Generated by Django 3.2.8 on 2022-07-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_datafwi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafwi',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='datafwi',
            name='Time_Stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
