# Generated by Django 3.2.8 on 2022-07-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_auto_20220724_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ray', models.FloatField(null=True)),
                ('dateRay', models.DateTimeField(null=True)),
            ],
        ),
    ]
