# Generated by Django 3.2.14 on 2022-10-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_ray'),
    ]

    operations = [
        migrations.CreateModel(
            name='ET0o',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('WSavg', models.FloatField(null=True)),
                ('Tmax', models.FloatField(null=True)),
                ('Tmin', models.FloatField(null=True)),
                ('Hmax', models.FloatField(null=True)),
                ('Hmin', models.FloatField(null=True)),
                ('Raym', models.FloatField(null=True)),
                ('U2', models.FloatField(null=True)),
                ('Delta', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(auto_now_add=True)),
                ('dt', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
