# Generated by Django 3.2.14 on 2022-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_et0o'),
    ]

    operations = [
        migrations.CreateModel(
            name='batvanne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bat', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
