# Generated by Django 3.2.14 on 2022-10-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_batvanne'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vanne',
            new_name='vann',
        ),
    ]
