# Generated by Django 3.2.14 on 2022-10-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_vann_og'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vann',
            name='og',
        ),
    ]
