# Generated by Django 3.2.14 on 2022-10-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_remove_vann_og'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='diff',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
