# Generated by Django 3.2.14 on 2022-11-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_data_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vann',
            name='onoff',
            field=models.BooleanField(),
        ),
    ]
