# Generated by Django 3.2.14 on 2023-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_alter_vann_onoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='alt',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pr',
            field=models.FloatField(null=True),
        ),
    ]
