# Generated by Django 3.2.14 on 2023-05-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_data_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d',
            field=models.FloatField(null=True),
        ),
    ]
