# Generated by Django 3.2.14 on 2023-05-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20230515_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='et0o',
            name='i',
            field=models.IntegerField(null=True),
        ),
    ]
