# Generated by Django 3.2.14 on 2023-05-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0035_et0o_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafwio',
            name='i',
            field=models.IntegerField(null=True),
        ),
    ]
