# Generated by Django 3.2.14 on 2023-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_datafwio_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='diff',
        ),
        migrations.AddField(
            model_name='data',
            name='i',
            field=models.IntegerField(null=True),
        ),
    ]
