# Generated by Django 3.2.14 on 2023-05-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0037_auto_20230518_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Wind_Dir',
        ),
    ]
