# Generated by Django 4.0.6 on 2023-08-31 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_remove_data_wind_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Time_Stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='et0o',
            name='Time_Stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
