# Generated by Django 4.0.6 on 2023-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0039_alter_data_time_stamp_alter_et0o_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ray2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ray', models.FloatField(null=True)),
                ('dateRay', models.DateTimeField(null=True)),
            ],
        ),
    ]
