# Generated by Django 4.0.6 on 2023-10-18 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0040_ray2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ray2',
            name='dateRay',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
