# Generated by Django 4.0.6 on 2023-10-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0041_alter_ray2_dateray'),
    ]

    operations = [
        migrations.AddField(
            model_name='ray2',
            name='Bat',
            field=models.FloatField(null=True),
        ),
    ]
