# Generated by Django 4.0.6 on 2023-10-18 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_ray2_bat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Device', models.IntegerField()),
                ('Temp', models.FloatField(null=True)),
                ('Hum', models.FloatField(null=True)),
                ('Wind_Speed', models.FloatField(null=True)),
                ('Rain', models.FloatField(null=True)),
                ('Bat', models.FloatField(null=True)),
                ('alt', models.FloatField(null=True)),
                ('pr', models.FloatField(null=True)),
                ('d', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
