# Generated by Django 4.0.6 on 2024-01-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_data2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm10', models.FloatField()),
                ('pm25', models.FloatField()),
                ('pm', models.FloatField()),
                ('co2', models.FloatField()),
                ('ch2o', models.FloatField()),
                ('o3', models.FloatField()),
                ('co', models.FloatField()),
                ('tvoc', models.FloatField()),
                ('no2', models.FloatField()),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('bat', models.FloatField()),
                ('Time_Stamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
