# Generated by Django 4.0.6 on 2024-01-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_envdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='envdata',
            name='devId',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
