# Generated by Django 4.0.6 on 2024-07-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_alter_envdata_devid'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ta', models.FloatField()),
                ('Tc', models.FloatField()),
                ('Time_Stamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
