# Generated by Django 4.0.6 on 2024-07-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_cwsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwsi',
            name='cw',
            field=models.FloatField(null=True),
        ),
    ]
