# Generated by Django 4.0.6 on 2024-07-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_remove_cwsi_cw'),
    ]

    operations = [
        migrations.CreateModel(
            name='cwsiO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
