# Generated by Django 4.0.6 on 2024-07-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_cwsio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data2',
            name='ID_Device',
        ),
        migrations.RemoveField(
            model_name='data2',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='data2',
            name='d',
        ),
        migrations.RemoveField(
            model_name='data2',
            name='pr',
        ),
    ]
