# Generated by Django 4.0.6 on 2024-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_remove_data2_id_device_remove_data2_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data2',
            name='pr',
            field=models.FloatField(null=True),
        ),
    ]
