# Generated by Django 4.0.6 on 2024-07-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_data2_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data2',
            name='Bat',
        ),
    ]
