# Generated by Django 4.0.6 on 2024-07-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_remove_data2_bat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data2',
            old_name='pr',
            new_name='Bat',
        ),
        migrations.RenameField(
            model_name='ray2',
            old_name='dateRay',
            new_name='DateRay',
        ),
        migrations.AddField(
            model_name='data2',
            name='Pr',
            field=models.FloatField(null=True),
        ),
    ]
