# Generated by Django 4.0.6 on 2024-07-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_remove_data2_bat'),
    ]

    operations = [
        migrations.AddField(
            model_name='data2',
            name='Bat',
            field=models.FloatField(null=True),
        ),
    ]
