# Generated by Django 4.0.6 on 2024-07-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0056_data2_bat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data2',
            name='Bat',
        ),
    ]
