# Generated by Django 4.0.6 on 2024-10-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_remove_data2_bat'),
    ]

    operations = [
        migrations.AddField(
            model_name='envdata',
            name='last_iaq_calculation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
