# Generated by Django 4.0.6 on 2024-10-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_envdata_last_iaq_calculation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envdata',
            old_name='last_iaq_calculation',
            new_name='last_calculation_S1',
        ),
        migrations.AddField(
            model_name='envdata',
            name='last_calculation_S2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envdata',
            name='last_calculation_S3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
