# Generated by Django 4.0.6 on 2025-03-06 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0059_rename_last_iaq_calculation_envdata_last_calculation_s1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_direction_angle', models.FloatField(null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('HUM', models.FloatField(null=True)),
                ('rain_gauge', models.FloatField(null=True)),
                ('wind_speed', models.FloatField(null=True)),
                ('illumination', models.FloatField(null=True)),
                ('TEM', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
