# Generated by Django 4.0.6 on 2025-03-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_et0executionlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsol',
            old_name='Sal',
            new_name='K',
        ),
        migrations.RenameField(
            model_name='capsol2',
            old_name='Sal',
            new_name='K',
        ),
        migrations.AddField(
            model_name='capsol',
            name='N',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='capsol',
            name='P',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='capsol2',
            name='N',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='capsol2',
            name='P',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='capsol2',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
