# Generated by Django 4.0.6 on 2025-03-29 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_rename_sal_capsol_k_rename_sal_capsol2_k_capsol_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ET0DR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('WSavg', models.FloatField()),
                ('Tmax', models.FloatField()),
                ('Tmin', models.FloatField()),
                ('Hmax', models.FloatField()),
                ('Hmin', models.FloatField()),
                ('Raym', models.FloatField()),
                ('U2', models.FloatField()),
                ('Delta', models.IntegerField()),
                ('Time_Stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='capsol',
            old_name='Ec',
            new_name='Sal',
        ),
        migrations.RenameField(
            model_name='capsol',
            old_name='K',
            new_name='ec',
        ),
        migrations.RenameField(
            model_name='capsol2',
            old_name='Ec',
            new_name='Sal',
        ),
        migrations.RenameField(
            model_name='capsol2',
            old_name='K',
            new_name='ec',
        ),
        migrations.RemoveField(
            model_name='capsol',
            name='N',
        ),
        migrations.RemoveField(
            model_name='capsol',
            name='P',
        ),
        migrations.RemoveField(
            model_name='capsol2',
            name='N',
        ),
        migrations.RemoveField(
            model_name='capsol2',
            name='P',
        ),
    ]
