# Generated by Django 4.0.6 on 2025-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0063_et0dr_rename_ec_capsol_sal_rename_k_capsol_ec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsol2',
            name='K',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='capsol2',
            name='N',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='capsol2',
            name='P',
            field=models.FloatField(null=True),
        ),
    ]
