# Generated by Django 4.0.6 on 2025-04-07 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_capsol2_k_capsol2_n_capsol2_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='debitcap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(null=True)),
                ('pulse', models.FloatField(null=True)),
                ('flag', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
