# Generated by Django 4.0.6 on 2025-04-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_debitcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='et0dr',
            name='Tavg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='et0o',
            name='Tavg',
            field=models.FloatField(null=True),
        ),
    ]
