# Generated by Django 4.0.6 on 2025-04-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_et0dr_tavg_et0o_tavg'),
    ]

    operations = [
        migrations.AddField(
            model_name='wsd',
            name='Rg',
            field=models.FloatField(null=True),
        ),
    ]
