# Generated by Django 4.0.6 on 2025-04-14 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_wsd_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ev_batt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batt', models.FloatField(null=True)),
                ('Time_Stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
