# Generated by Django 4.0.6 on 2025-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_ev_batt'),
    ]

    operations = [
        migrations.AddField(
            model_name='data2',
            name='Rain_acc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='data2',
            name='Rain_act',
            field=models.FloatField(null=True),
        ),
    ]
